### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by jorisroling** [jbmorley/ISListViewAdapter#1]
Should line 24 in **ISListViewAdapterChanges.h** not read  `#import "ISListViewAdapterOperation.h"` instead of `#import "ISListViewAdapterOperation.m"`?

J*

**Comment by jbmorley** [comment]
@jorisroling Definitely a typo!

Fixed in f5b77dc287ef0b63f30a8162c97c19b7376a26fb. Sorry for taking my time making the change. I'll try to push out a CocoaPod update in the next day or two.
